apiVersion: v1
kind: Service
metadata:
  name: sample-web-service
  labels:
    app: sample-web-app
spec:
  selector:
    app: sample-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
