apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-web-app-monitor
  namespace: monitoring
  labels:
    app: sample-web-app
spec:
  selector:
    matchLabels:
      app: sample-web-app
  endpoints:
  - port: web
    interval: 30s
    path: /metrics
