apiVersion: v1
kind: Pod
metadata:
  name: failing-webapp
  labels:
    app: failing-webapp
spec:
  containers:
  - name: webapp
    image: nginx:1.21
    ports:
    - containerPort: 80
    # Intentionally failing liveness probe
    livenessProbe:
      httpGet:
        path: /nonexistent
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 2
    # Intentionally failing readiness probe
    readinessProbe:
      httpGet:
        path: /nonexistent
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 2
