apiVersion: v1
kind: Pod
metadata:
  name: logging-app
spec:
  containers:
  - name: logger
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      counter=1
      while true; do
        echo "$(date): Log entry #$counter - Application is running normally"
        if [ $((counter % 5)) -eq 0 ]; then
          echo "$(date): WARNING - High memory usage detected"
        fi
        if [ $((counter % 10)) -eq 0 ]; then
          echo "$(date): ERROR - Simulated error condition" >&2
        fi
        counter=$((counter + 1))
        sleep 2
      done
