apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
spec:
  containers:
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: log-processor
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      while true; do
        echo "$(date): Processing logs from web server"
        sleep 10
      done
