apiVersion: v1
kind: Pod
metadata:
  name: problematic-app
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    # Misconfigured volume mount
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
  volumes:
  - name: config-volume
    configMap:
      name: nonexistent-config
