apiVersion: v1
kind: Pod
metadata:
  name: custom-security-pod
spec:
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
    supplementalGroups: [3000, 4000]
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: custom-container
    image: nginx:1.21
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
