apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  labels:
    app: privileged-test
spec:
  containers:
  - name: privileged-container
    image: nginx:1.21
    securityContext:
      privileged: true
      runAsUser: 0
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
