apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: network-debug
spec:
  containers:
  - name: debug-tools
    image: nicolaka/netshoot:latest
    command: ['sleep', '3600']
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
